name: Feature Request
description: 새로운 기능 추가
title: ":sparkles: feat : "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature
    attributes:
      label: 내용
      description: 추가하고자 하는 기능에 대하여 설명해주세요.
      value: |
        -
    validations:
      required: true
