name: Refactoring
description: 코드 리팩토링
title: ":recycle: refactor : "
labels: ["refactoring"]
body:
  - type: textarea
    id: feature
    attributes:
      label: 내용
      description: 리팩토링한 부분에 대하여 설명해주세요.
      value: |
        -
    validations:
      required: true
